export const starterExercises = [
    // 10 Compound Lifts
    {
        _id: 'ex_bench_press',
        name: 'Barbell Bench Press',
        primaryMuscles: ['chest_left', 'chest_right'],
        secondaryMuscles: ['shoulder_front_left', 'shoulder_front_right', 'tricep_left', 'tricep_right'],
        equipment: 'Barbell',
        isStarter: true,
    },
    {
        _id: 'ex_squat',
        name: 'Barbell Back Squat',
        primaryMuscles: ['quads_left', 'quads_right', 'glutes'],
        secondaryMuscles: ['hamstrings_left', 'hamstrings_right', 'lower_back'],
        equipment: 'Barbell',
        isStarter: true,
    },
    {
        _id: 'ex_deadlift',
        name: 'Conventional Deadlift',
        primaryMuscles: ['lower_back', 'glutes', 'hamstrings_left', 'hamstrings_right'],
        secondaryMuscles: ['traps', 'lats', 'forearms'],
        equipment: 'Barbell',
        isStarter: true,
    },
    {
        _id: 'ex_ohp',
        name: 'Overhead Press',
        primaryMuscles: ['shoulder_front_left', 'shoulder_front_right', 'shoulder_mid_left', 'shoulder_mid_right'],
        secondaryMuscles: ['tricep_left', 'tricep_right', 'traps'],
        equipment: 'Barbell',
        isStarter: true,
    },
    {
        _id: 'ex_barbell_row',
        name: 'Barbell Row',
        primaryMuscles: ['lats', 'rhomboids'],
        secondaryMuscles: ['bicep_left', 'bicep_right', 'lower_back'],
        equipment: 'Barbell',
        isStarter: true,
    },
    {
        _id: 'ex_pullups',
        name: 'Pull-Ups',
        primaryMuscles: ['lats', 'bicep_left', 'bicep_right'],
        secondaryMuscles: ['rhomboids', 'traps'],
        equipment: 'Bodyweight',
        isStarter: true,
    },
    {
        _id: 'ex_dips',
        name: 'Dips',
        primaryMuscles: ['chest_left', 'chest_right', 'tricep_left', 'tricep_right'],
        secondaryMuscles: ['shoulder_front_left', 'shoulder_front_right'],
        equipment: 'Bodyweight',
        isStarter: true,
    },
    {
        _id: 'ex_incline_db_press',
        name: 'Incline DB Press',
        primaryMuscles: ['chest_upper_left', 'chest_upper_right'],
        secondaryMuscles: ['shoulder_front_left', 'shoulder_front_right', 'tricep_left', 'tricep_right'],
        equipment: 'Dumbbell',
        isStarter: true,
    },
    {
        _id: 'ex_leg_press',
        name: 'Leg Press',
        primaryMuscles: ['quads_left', 'quads_right'],
        secondaryMuscles: ['glutes', 'hamstrings_left', 'hamstrings_right'],
        equipment: 'Machine',
        isStarter: true,
    },
    {
        _id: 'ex_romanian_deadlift',
        name: 'Romanian Deadlift',
        primaryMuscles: ['hamstrings_left', 'hamstrings_right', 'glutes'],
        secondaryMuscles: ['lower_back', 'forearms'],
        equipment: 'Barbell',
        isStarter: true,
    },

    // 15 Machine/Isolation
    {
        _id: 'ex_lat_pulldown',
        name: 'Lat Pulldown',
        primaryMuscles: ['lats'],
        secondaryMuscles: ['bicep_left', 'bicep_right'],
        equipment: 'Machine',
        isStarter: true,
    },
    {
        _id: 'ex_cable_fly',
        name: 'Cable Fly',
        primaryMuscles: ['chest_left', 'chest_right'],
        secondaryMuscles: ['shoulder_front_left', 'shoulder_front_right'],
        equipment: 'Cable',
        isStarter: true,
    },
    {
        _id: 'ex_bicep_curl',
        name: 'Dumbbell Bicep Curl',
        primaryMuscles: ['bicep_left', 'bicep_right'],
        secondaryMuscles: ['forearms'],
        equipment: 'Dumbbell',
        isStarter: true,
    },
    {
        _id: 'ex_lateral_raise',
        name: 'Lateral Raise',
        primaryMuscles: ['shoulder_mid_left', 'shoulder_mid_right'],
        secondaryMuscles: ['traps'],
        equipment: 'Dumbbell',
        isStarter: true,
    },
    {
        _id: 'ex_tricep_pushdown',
        name: 'Tricep Pushdown',
        primaryMuscles: ['tricep_left', 'tricep_right'],
        secondaryMuscles: [],
        equipment: 'Cable',
        isStarter: true,
    },
    {
        _id: 'ex_leg_extension',
        name: 'Leg Extension',
        primaryMuscles: ['quads_left', 'quads_right'],
        secondaryMuscles: [],
        equipment: 'Machine',
        isStarter: true,
    },
    {
        _id: 'ex_leg_curl',
        name: 'Leg Curl',
        primaryMuscles: ['hamstrings_left', 'hamstrings_right'],
        secondaryMuscles: [],
        equipment: 'Machine',
        isStarter: true,
    },
    {
        _id: 'ex_calf_raise',
        name: 'Calf Raise',
        primaryMuscles: ['calves_left', 'calves_right'],
        secondaryMuscles: [],
        equipment: 'Machine',
        isStarter: true,
    },
    {
        _id: 'ex_face_pulls',
        name: 'Face Pulls',
        primaryMuscles: ['shoulder_rear_left', 'shoulder_rear_right', 'traps'],
        secondaryMuscles: ['rhomboids'],
        equipment: 'Cable',
        isStarter: true,
    },
    {
        _id: 'ex_hammer_curl',
        name: 'Hammer Curl',
        primaryMuscles: ['bicep_left', 'bicep_right', 'forearms'],
        secondaryMuscles: [],
        equipment: 'Dumbbell',
        isStarter: true,
    },
    {
        _id: 'ex_skull_crushers',
        name: 'Skull Crushers',
        primaryMuscles: ['tricep_left', 'tricep_right'],
        secondaryMuscles: [],
        equipment: 'Barbell',
        isStarter: true,
    },
    {
        _id: 'ex_seated_row',
        name: 'Seated Cable Row',
        primaryMuscles: ['lats', 'rhomboids'],
        secondaryMuscles: ['bicep_left', 'bicep_right'],
        equipment: 'Cable',
        isStarter: true,
    },
    {
        _id: 'ex_leg_press_calf_raise',
        name: 'Leg Press Calf Raise',
        primaryMuscles: ['calves_left', 'calves_right'],
        secondaryMuscles: [],
        equipment: 'Machine',
        isStarter: true,
    },
    {
        _id: 'ex_rope_hammer_curl',
        name: 'Rope Hammer Curl',
        primaryMuscles: ['bicep_left', 'bicep_right', 'forearms'],
        secondaryMuscles: [],
        equipment: 'Cable',
        isStarter: true,
    },
    {
        _id: 'ex_pec_deck',
        name: 'Pec Deck',
        primaryMuscles: ['chest_left', 'chest_right'],
        secondaryMuscles: [],
        equipment: 'Machine',
        isStarter: true,
    },

    // 5 Bodyweight
    {
        _id: 'ex_pushups',
        name: 'Push-Ups',
        primaryMuscles: ['chest_left', 'chest_right', 'tricep_left', 'tricep_right'],
        secondaryMuscles: ['shoulder_front_left', 'shoulder_front_right'],
        equipment: 'Bodyweight',
        isStarter: true,
    },
    {
        _id: 'ex_lunges',
        name: 'Lunges',
        primaryMuscles: ['quads_left', 'quads_right', 'glutes'],
        secondaryMuscles: ['hamstrings_left', 'hamstrings_right'],
        equipment: 'Bodyweight',
        isStarter: true,
    },
    {
        _id: 'ex_plank',
        name: 'Plank',
        primaryMuscles: ['abs'],
        secondaryMuscles: ['obliques', 'shoulders'],
        equipment: 'Bodyweight',
        isStarter: true,
    },
    {
        _id: 'ex_hanging_leg_raise',
        name: 'Hanging Leg Raise',
        primaryMuscles: ['abs'],
        secondaryMuscles: ['forearms'],
        equipment: 'Bodyweight',
        isStarter: true,
    },
    {
        _id: 'ex_chin_ups',
        name: 'Chin-Ups',
        primaryMuscles: ['lats', 'bicep_left', 'bicep_right'],
        secondaryMuscles: ['rhomboids'],
        equipment: 'Bodyweight',
        isStarter: true,
    },
];
