import { EquipmentType, Exercise } from './db';

export const starterExercises: Omit<Exercise, 'id'>[] = [
    // --- COMPOUND LIFTS (10) ---
    {
        name: 'Barbell Bench Press',
        primaryMuscles: ['chest'],
        secondaryMuscles: ['triceps', 'shoulders'],
        equipment: 'Barbell',
        repRange: '6-10',
        isStarter: true,
    },
    {
        name: 'Barbell Back Squat',
        primaryMuscles: ['quads', 'glutes'],
        secondaryMuscles: ['hamstrings', 'abs'],
        equipment: 'Barbell',
        repRange: '6-10',
        isStarter: true,
    },
    {
        name: 'Conventional Deadlift',
        primaryMuscles: ['hamstrings', 'glutes', 'lower_back'],
        secondaryMuscles: ['traps', 'forearms', 'lats'],
        equipment: 'Barbell',
        repRange: '5-8',
        isStarter: true,
    },
    {
        name: 'Overhead Press',
        primaryMuscles: ['shoulders'],
        secondaryMuscles: ['triceps', 'abs'],
        equipment: 'Barbell',
        repRange: '6-10',
        isStarter: true,
    },
    {
        name: 'Barbell Row',
        primaryMuscles: ['lats', 'rhomboids'],
        secondaryMuscles: ['biceps', 'rear_delts', 'traps'],
        equipment: 'Barbell',
        repRange: '6-10',
        isStarter: true,
    },
    {
        name: 'Pull-ups',
        primaryMuscles: ['lats'],
        secondaryMuscles: ['biceps', 'forearms', 'rhomboids'],
        equipment: 'Bodyweight',
        repRange: '6-12',
        isStarter: true,
    },
    {
        name: 'Dips',
        primaryMuscles: ['chest', 'triceps'],
        secondaryMuscles: ['shoulders'],
        equipment: 'Bodyweight',
        repRange: '8-12',
        isStarter: true,
    },
    {
        name: 'Romanian Deadlift',
        primaryMuscles: ['hamstrings', 'glutes'],
        secondaryMuscles: ['lower_back'],
        equipment: 'Barbell',
        repRange: '8-12',
        isStarter: true,
    },
    {
        name: 'Incline Bench Press',
        primaryMuscles: ['chest'],
        secondaryMuscles: ['shoulders', 'triceps'],
        equipment: 'Barbell',
        repRange: '6-10',
        isStarter: true,
    },
    {
        name: 'Leg Press',
        primaryMuscles: ['quads', 'glutes'],
        secondaryMuscles: ['hamstrings'],
        equipment: 'Machine',
        repRange: '8-12',
        isStarter: true,
    },

    // --- ISOLATION / MACHINE (15) ---
    {
        name: 'Lat Pulldown',
        primaryMuscles: ['lats'],
        secondaryMuscles: ['biceps', 'rhomboids'],
        equipment: 'Cable',
        repRange: '8-12',
        isStarter: true,
    },
    {
        name: 'Cable Fly',
        primaryMuscles: ['chest'],
        secondaryMuscles: [],
        equipment: 'Cable',
        repRange: '10-15',
        isStarter: true,
    },
    {
        name: 'Tricep Pushdown',
        primaryMuscles: ['triceps'],
        secondaryMuscles: [],
        equipment: 'Cable',
        repRange: '10-15',
        isStarter: true,
    },
    {
        name: 'Bicep Curl',
        primaryMuscles: ['biceps'],
        secondaryMuscles: ['forearms'],
        equipment: 'Dumbbell',
        repRange: '10-15',
        isStarter: true,
    },
    {
        name: 'Lateral Raise',
        primaryMuscles: ['shoulders'],
        secondaryMuscles: [],
        equipment: 'Dumbbell',
        repRange: '12-15',
        isStarter: true,
    },
    {
        name: 'Face Pull',
        primaryMuscles: ['rear_delts', 'traps'],
        secondaryMuscles: ['rhomboids'],
        equipment: 'Cable',
        repRange: '12-15',
        isStarter: true,
    },
    {
        name: 'Leg Curl',
        primaryMuscles: ['hamstrings'],
        secondaryMuscles: [],
        equipment: 'Machine',
        repRange: '10-15',
        isStarter: true,
    },
    {
        name: 'Leg Extension',
        primaryMuscles: ['quads'],
        secondaryMuscles: [],
        equipment: 'Machine',
        repRange: '10-15',
        isStarter: true,
    },
    {
        name: 'Calf Raise',
        primaryMuscles: ['calves'],
        secondaryMuscles: [],
        equipment: 'Machine',
        repRange: '12-20',
        isStarter: true,
    },
    {
        name: 'Cable Row',
        primaryMuscles: ['lats', 'rhomboids'],
        secondaryMuscles: ['biceps', 'rear_delts'],
        equipment: 'Cable',
        repRange: '8-12',
        isStarter: true,
    },
    {
        name: 'Chest Press Machine',
        primaryMuscles: ['chest'],
        secondaryMuscles: ['triceps', 'shoulders'],
        equipment: 'Machine',
        repRange: '8-12',
        isStarter: true,
    },
    {
        name: 'Shoulder Press Machine',
        primaryMuscles: ['shoulders'],
        secondaryMuscles: ['triceps'],
        equipment: 'Machine',
        repRange: '8-12',
        isStarter: true,
    },
    {
        name: 'Hammer Curl',
        primaryMuscles: ['biceps', 'forearms'],
        secondaryMuscles: [],
        equipment: 'Dumbbell',
        repRange: '10-12',
        isStarter: true,
    },
    {
        name: 'Skull Crushers',
        primaryMuscles: ['triceps'],
        secondaryMuscles: [],
        equipment: 'EZ Bar',
        repRange: '8-12',
        isStarter: true,
    },
    {
        name: 'Hip Thrust',
        primaryMuscles: ['glutes'],
        secondaryMuscles: ['hamstrings'],
        equipment: 'Barbell',
        repRange: '8-12',
        isStarter: true,
    },

    // --- BODYWEIGHT (5) ---
    {
        name: 'Push-ups',
        primaryMuscles: ['chest'],
        secondaryMuscles: ['triceps', 'shoulders', 'abs'],
        equipment: 'Bodyweight',
        repRange: '10-20',
        isStarter: true,
    },
    {
        name: 'Plank',
        primaryMuscles: ['abs'],
        secondaryMuscles: ['shoulders', 'obliques'],
        equipment: 'Bodyweight',
        repRange: '30-60s',
        isStarter: true,
    },
    {
        name: 'Lunges',
        primaryMuscles: ['quads', 'glutes'],
        secondaryMuscles: ['hamstrings'],
        equipment: 'Bodyweight',
        repRange: '10-15',
        isStarter: true,
    },
    {
        name: 'Chin-ups',
        primaryMuscles: ['biceps', 'lats'],
        secondaryMuscles: ['forearms', 'rhomboids'],
        equipment: 'Bodyweight',
        repRange: '6-10',
        isStarter: true,
    },
    {
        name: 'Hanging Leg Raise',
        primaryMuscles: ['abs'],
        secondaryMuscles: ['obliques'],
        equipment: 'Bodyweight',
        repRange: '10-15',
        isStarter: true,
    },
];
