import { Exercise } from './db';

export const starterExercises: Omit<Exercise, 'id'>[] = [
    // --- COMPOUND LIFTS (10) ---
    {
        name: 'Barbell Bench Press',
        primaryMuscles: ['chest'],
        secondaryMuscles: ['triceps', 'shoulders'],
        equipment: 'Barbell',
        isStarter: true,
    },
    {
        name: 'Barbell Back Squat',
        primaryMuscles: ['quads', 'glutes'],
        secondaryMuscles: ['hamstrings', 'core'],
        equipment: 'Barbell',
        isStarter: true,
    },
    {
        name: 'Conventional Deadlift',
        primaryMuscles: ['back', 'hamstrings'],
        secondaryMuscles: ['glutes', 'traps', 'forearms'],
        equipment: 'Barbell',
        isStarter: true,
    },
    {
        name: 'Overhead Press',
        primaryMuscles: ['shoulders'],
        secondaryMuscles: ['triceps', 'core'],
        equipment: 'Barbell',
        isStarter: true,
    },
    {
        name: 'Barbell Row',
        primaryMuscles: ['back'],
        secondaryMuscles: ['biceps', 'rear_delts'],
        equipment: 'Barbell',
        isStarter: true,
    },
    {
        name: 'Pull-ups',
        primaryMuscles: ['lats', 'back'],
        secondaryMuscles: ['biceps', 'forearms'],
        equipment: 'Bodyweight',
        isStarter: true,
    },
    {
        name: 'Dips',
        primaryMuscles: ['chest', 'triceps'],
        secondaryMuscles: ['shoulders'],
        equipment: 'Bodyweight',
        isStarter: true,
    },
    {
        name: 'Romanian Deadlift',
        primaryMuscles: ['hamstrings', 'glutes'],
        secondaryMuscles: ['back'],
        equipment: 'Barbell',
        isStarter: true,
    },
    {
        name: 'Incline Bench Press',
        primaryMuscles: ['chest'],
        secondaryMuscles: ['shoulders', 'triceps'],
        equipment: 'Barbell',
        isStarter: true,
    },
    {
        name: 'Leg Press',
        primaryMuscles: ['quads', 'glutes'],
        secondaryMuscles: ['hamstrings'],
        equipment: 'Machine',
        isStarter: true,
    },

    // --- ISOLATION / MACHINE (15) ---
    {
        name: 'Lat Pulldown',
        primaryMuscles: ['lats'],
        secondaryMuscles: ['biceps'],
        equipment: 'Cable',
        isStarter: true,
    },
    {
        name: 'Cable Fly',
        primaryMuscles: ['chest'],
        secondaryMuscles: [],
        equipment: 'Cable',
        isStarter: true,
    },
    {
        name: 'Tricep Pushdown',
        primaryMuscles: ['triceps'],
        secondaryMuscles: [],
        equipment: 'Cable',
        isStarter: true,
    },
    {
        name: 'Bicep Curl',
        primaryMuscles: ['biceps'],
        secondaryMuscles: ['forearms'],
        equipment: 'Dumbbell',
        isStarter: true,
    },
    {
        name: 'Lateral Raise',
        primaryMuscles: ['shoulders'],
        secondaryMuscles: [],
        equipment: 'Dumbbell',
        isStarter: true,
    },
    {
        name: 'Face Pull',
        primaryMuscles: ['rear_delts', 'traps'],
        secondaryMuscles: [],
        equipment: 'Cable',
        isStarter: true,
    },
    {
        name: 'Leg Curl',
        primaryMuscles: ['hamstrings'],
        secondaryMuscles: [],
        equipment: 'Machine',
        isStarter: true,
    },
    {
        name: 'Leg Extension',
        primaryMuscles: ['quads'],
        secondaryMuscles: [],
        equipment: 'Machine',
        isStarter: true,
    },
    {
        name: 'Calf Raise',
        primaryMuscles: ['calves'],
        secondaryMuscles: [],
        equipment: 'Machine',
        isStarter: true,
    },
    {
        name: 'Cable Row',
        primaryMuscles: ['back'],
        secondaryMuscles: ['biceps'],
        equipment: 'Cable',
        isStarter: true,
    },
    {
        name: 'Chest Press Machine',
        primaryMuscles: ['chest'],
        secondaryMuscles: ['triceps', 'shoulders'],
        equipment: 'Machine',
        isStarter: true,
    },
    {
        name: 'Shoulder Press Machine',
        primaryMuscles: ['shoulders'],
        secondaryMuscles: ['triceps'],
        equipment: 'Machine',
        isStarter: true,
    },
    {
        name: 'Hammer Curl',
        primaryMuscles: ['biceps', 'forearms'],
        secondaryMuscles: [],
        equipment: 'Dumbbell',
        isStarter: true,
    },
    {
        name: 'Skull Crushers',
        primaryMuscles: ['triceps'],
        secondaryMuscles: [],
        equipment: 'EZ Bar',
        isStarter: true,
    },
    {
        name: 'Hip Thrust',
        primaryMuscles: ['glutes'],
        secondaryMuscles: ['hamstrings'],
        equipment: 'Barbell',
        isStarter: true,
    },

    // --- BODYWEIGHT (5) ---
    {
        name: 'Push-ups',
        primaryMuscles: ['chest'],
        secondaryMuscles: ['triceps', 'shoulders', 'core'],
        equipment: 'Bodyweight',
        isStarter: true,
    },
    {
        name: 'Plank',
        primaryMuscles: ['core'],
        secondaryMuscles: ['shoulders'],
        equipment: 'Bodyweight',
        isStarter: true,
    },
    {
        name: 'Lunges',
        primaryMuscles: ['quads', 'glutes'],
        secondaryMuscles: ['hamstrings'],
        equipment: 'Bodyweight',
        isStarter: true,
    },
    {
        name: 'Chin-ups',
        primaryMuscles: ['biceps', 'lats'],
        secondaryMuscles: ['forearms'],
        equipment: 'Bodyweight',
        isStarter: true,
    },
    {
        name: 'Hanging Leg Raise',
        primaryMuscles: ['core'],
        secondaryMuscles: ['hip_flexors'],
        equipment: 'Bodyweight',
        isStarter: true,
    },
];
